<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerP6Dryyl\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerP6Dryyl/App_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerP6Dryyl.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\ContainerP6Dryyl\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \ContainerP6Dryyl\App_KernelProdContainer([
    'container.build_hash' => 'P6Dryyl',
    'container.build_id' => '8ba28d83',
    'container.build_time' => 1749519171,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerP6Dryyl');
