<?php

namespace Proxies\__CG__\App\Module\Users\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class User extends \App\Module\Users\Entity\User implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as __load;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'addressCity' => [parent::class, 'addressCity', null],
        "\0".parent::class."\0".'addressCountry' => [parent::class, 'addressCountry', null],
        "\0".parent::class."\0".'addressPostalcode' => [parent::class, 'addressPostalcode', null],
        "\0".parent::class."\0".'addressState' => [parent::class, 'addressState', null],
        "\0".parent::class."\0".'addressStreet' => [parent::class, 'addressStreet', null],
        "\0".parent::class."\0".'authenticateId' => [parent::class, 'authenticateId', null],
        "\0".parent::class."\0".'backupCodes' => [parent::class, 'backupCodes', null],
        "\0".parent::class."\0".'createdBy' => [parent::class, 'createdBy', null],
        "\0".parent::class."\0".'dateEntered' => [parent::class, 'dateEntered', null],
        "\0".parent::class."\0".'dateModified' => [parent::class, 'dateModified', null],
        "\0".parent::class."\0".'deleted' => [parent::class, 'deleted', null],
        "\0".parent::class."\0".'department' => [parent::class, 'department', null],
        "\0".parent::class."\0".'description' => [parent::class, 'description', null],
        "\0".parent::class."\0".'employeeStatus' => [parent::class, 'employeeStatus', null],
        "\0".parent::class."\0".'externalAuthOnly' => [parent::class, 'externalAuthOnly', null],
        "\0".parent::class."\0".'factorAuth' => [parent::class, 'factorAuth', null],
        "\0".parent::class."\0".'factorAuthInterface' => [parent::class, 'factorAuthInterface', null],
        "\0".parent::class."\0".'firstName' => [parent::class, 'firstName', null],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null],
        "\0".parent::class."\0".'isAdmin' => [parent::class, 'isAdmin', null],
        "\0".parent::class."\0".'isGroup' => [parent::class, 'isGroup', null],
        "\0".parent::class."\0".'isTotpEnabled' => [parent::class, 'isTotpEnabled', null],
        "\0".parent::class."\0".'lastName' => [parent::class, 'lastName', null],
        "\0".parent::class."\0".'messengerId' => [parent::class, 'messengerId', null],
        "\0".parent::class."\0".'messengerType' => [parent::class, 'messengerType', null],
        "\0".parent::class."\0".'modifiedUserId' => [parent::class, 'modifiedUserId', null],
        "\0".parent::class."\0".'phoneFax' => [parent::class, 'phoneFax', null],
        "\0".parent::class."\0".'phoneHome' => [parent::class, 'phoneHome', null],
        "\0".parent::class."\0".'phoneMobile' => [parent::class, 'phoneMobile', null],
        "\0".parent::class."\0".'phoneOther' => [parent::class, 'phoneOther', null],
        "\0".parent::class."\0".'phoneWork' => [parent::class, 'phoneWork', null],
        "\0".parent::class."\0".'photo' => [parent::class, 'photo', null],
        "\0".parent::class."\0".'portalOnly' => [parent::class, 'portalOnly', null],
        "\0".parent::class."\0".'pwdLastChanged' => [parent::class, 'pwdLastChanged', null],
        "\0".parent::class."\0".'receiveNotifications' => [parent::class, 'receiveNotifications', null],
        "\0".parent::class."\0".'reportsToId' => [parent::class, 'reportsToId', null],
        "\0".parent::class."\0".'showOnEmployees' => [parent::class, 'showOnEmployees', null],
        "\0".parent::class."\0".'status' => [parent::class, 'status', null],
        "\0".parent::class."\0".'sugarLogin' => [parent::class, 'sugarLogin', null],
        "\0".parent::class."\0".'systemGeneratedPassword' => [parent::class, 'systemGeneratedPassword', null],
        "\0".parent::class."\0".'title' => [parent::class, 'title', null],
        "\0".parent::class."\0".'totpSecret' => [parent::class, 'totpSecret', null],
        "\0".parent::class."\0".'userHash' => [parent::class, 'userHash', null],
        "\0".parent::class."\0".'user_name' => [parent::class, 'user_name', null],
        'addressCity' => [parent::class, 'addressCity', null],
        'addressCountry' => [parent::class, 'addressCountry', null],
        'addressPostalcode' => [parent::class, 'addressPostalcode', null],
        'addressState' => [parent::class, 'addressState', null],
        'addressStreet' => [parent::class, 'addressStreet', null],
        'authenticateId' => [parent::class, 'authenticateId', null],
        'backupCodes' => [parent::class, 'backupCodes', null],
        'createdBy' => [parent::class, 'createdBy', null],
        'dateEntered' => [parent::class, 'dateEntered', null],
        'dateModified' => [parent::class, 'dateModified', null],
        'deleted' => [parent::class, 'deleted', null],
        'department' => [parent::class, 'department', null],
        'description' => [parent::class, 'description', null],
        'employeeStatus' => [parent::class, 'employeeStatus', null],
        'externalAuthOnly' => [parent::class, 'externalAuthOnly', null],
        'factorAuth' => [parent::class, 'factorAuth', null],
        'factorAuthInterface' => [parent::class, 'factorAuthInterface', null],
        'firstName' => [parent::class, 'firstName', null],
        'id' => [parent::class, 'id', null],
        'isAdmin' => [parent::class, 'isAdmin', null],
        'isGroup' => [parent::class, 'isGroup', null],
        'isTotpEnabled' => [parent::class, 'isTotpEnabled', null],
        'lastName' => [parent::class, 'lastName', null],
        'messengerId' => [parent::class, 'messengerId', null],
        'messengerType' => [parent::class, 'messengerType', null],
        'modifiedUserId' => [parent::class, 'modifiedUserId', null],
        'phoneFax' => [parent::class, 'phoneFax', null],
        'phoneHome' => [parent::class, 'phoneHome', null],
        'phoneMobile' => [parent::class, 'phoneMobile', null],
        'phoneOther' => [parent::class, 'phoneOther', null],
        'phoneWork' => [parent::class, 'phoneWork', null],
        'photo' => [parent::class, 'photo', null],
        'portalOnly' => [parent::class, 'portalOnly', null],
        'pwdLastChanged' => [parent::class, 'pwdLastChanged', null],
        'receiveNotifications' => [parent::class, 'receiveNotifications', null],
        'reportsToId' => [parent::class, 'reportsToId', null],
        'showOnEmployees' => [parent::class, 'showOnEmployees', null],
        'status' => [parent::class, 'status', null],
        'sugarLogin' => [parent::class, 'sugarLogin', null],
        'systemGeneratedPassword' => [parent::class, 'systemGeneratedPassword', null],
        'title' => [parent::class, 'title', null],
        'totpSecret' => [parent::class, 'totpSecret', null],
        'userHash' => [parent::class, 'userHash', null],
        'user_name' => [parent::class, 'user_name', null],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
