<?php

namespace ContainerP6Dryyl;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get2faFailedService extends App_KernelProdContainer
{
    /*
     * Gets the public '2fa_failed' shared autowired service.
     *
     * @return \App\Security\TwoFactor\TwoFactorAuthenticationFailureHandler
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 3).'/vendor/symfony/security-http/Authentication/AuthenticationFailureHandlerInterface.php';
        include_once \dirname(__DIR__, 3).'/core/backend/Security/TwoFactor/TwoFactorAuthenticationFailureHandler.php';

        return $container->services['2fa_failed'] = new \App\Security\TwoFactor\TwoFactorAuthenticationFailureHandler();
    }
}
