<?php

namespace ContainerP6Dryyl;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get2faRequiredService extends App_KernelProdContainer
{
    /*
     * Gets the public '2fa_required' shared autowired service.
     *
     * @return \App\Security\TwoFactor\TwoFactorAuthenticationRequiredHandler
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 3).'/vendor/scheb/2fa-bundle/Security/Http/Authentication/AuthenticationRequiredHandlerInterface.php';
        include_once \dirname(__DIR__, 3).'/core/backend/Security/TwoFactor/TwoFactorAuthenticationRequiredHandler.php';

        return $container->services['2fa_required'] = new \App\Security\TwoFactor\TwoFactorAuthenticationRequiredHandler();
    }
}
