<?php

namespace ContainerP6Dryyl;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ShivasVersioning_Command_ListProviders_LazyService extends App_KernelProdContainer
{
    /*
     * Gets the private '.shivas_versioning.command.list_providers.lazy' shared service.
     *
     * @return \Symfony\Component\Console\Command\LazyCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 3).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 3).'/vendor/symfony/console/Command/LazyCommand.php';

        return $container->privates['.shivas_versioning.command.list_providers.lazy'] = new \Symfony\Component\Console\Command\LazyCommand('app:version:list-providers', [], 'List all registered version providers', false, #[\Closure(name: 'shivas_versioning.command.list_providers', class: 'Shivas\\VersioningBundle\\Command\\ListProvidersCommand')] fn (): \Shivas\VersioningBundle\Command\ListProvidersCommand => ($container->privates['shivas_versioning.command.list_providers'] ?? $container->load('getShivasVersioning_Command_ListProvidersService')));
    }
}
