<?php

namespace ContainerP6Dryyl;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_ZNgsiq9Service extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.zNgsiq9' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.zNgsiq9'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'auth' => ['privates', '.errored..service_locator.zNgsiq9.OneLogin\\Saml2\\Auth', NULL, 'Cannot autowire service ".service_locator.zNgsiq9": it references class "OneLogin\\Saml2\\Auth" but no such service exists.'],
        ], [
            'auth' => 'OneLogin\\Saml2\\Auth',
        ]);
    }
}
