<?php

namespace ContainerP6Dryyl;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAssertionConsumerServiceService extends App_KernelProdContainer
{
    /*
     * Gets the public 'Nbgrp\OneloginSamlBundle\Controller\AssertionConsumerService' shared service.
     *
     * @return \Nbgrp\OneloginSamlBundle\Controller\AssertionConsumerService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 3).'/vendor/nbgrp/onelogin-saml-bundle/src/Controller/AssertionConsumerService.php';

        return $container->services['Nbgrp\\OneloginSamlBundle\\Controller\\AssertionConsumerService'] = new \Nbgrp\OneloginSamlBundle\Controller\AssertionConsumerService();
    }
}
