<?php

namespace ContainerP6Dryyl;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAuthService extends App_KernelProdContainer
{
    /*
     * Gets the private '.errored..service_locator.zNgsiq9.OneLogin\Saml2\Auth' shared service.
     *
     * @return \OneLogin\Saml2\Auth
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.zNgsiq9": it references class "OneLogin\\Saml2\\Auth" but no such service exists.');
    }
}
