<?php

namespace ContainerP6Dryyl;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getApiPlatform_Graphql_Action_GraphqlPlaygroundService extends App_KernelProdContainer
{
    /*
     * Gets the public 'api_platform.graphql.action.graphql_playground' shared service.
     *
     * @return \ApiPlatform\GraphQl\Action\GraphQlPlaygroundAction
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 3).'/vendor/api-platform/core/src/GraphQl/Action/GraphQlPlaygroundAction.php';

        return $container->services['api_platform.graphql.action.graphql_playground'] = new \ApiPlatform\GraphQl\Action\GraphQlPlaygroundAction(($container->privates['twig'] ?? $container->load('getTwigService')), ($container->privates['api_platform.router'] ?? self::getApiPlatform_RouterService($container)), true, 'SuiteCRM API', NULL);
    }
}
