<?php

namespace ContainerP6Dryyl;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAppCheckLdapCredentialsListenerService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Security\Ldap\AppCheckLdapCredentialsListener' shared autowired service.
     *
     * @return \App\Security\Ldap\AppCheckLdapCredentialsListener
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 3).'/vendor/symfony/ldap/Security/CheckLdapCredentialsListener.php';
        include_once \dirname(__DIR__, 3).'/core/backend/Security/Ldap/AppCheckLdapCredentialsListener.php';

        return $container->privates['App\\Security\\Ldap\\AppCheckLdapCredentialsListener'] = new \App\Security\Ldap\AppCheckLdapCredentialsListener(new \Symfony\Component\DependencyInjection\ServiceLocator(['Symfony\\Component\\Ldap\\Ldap' => #[\Closure(name: 'Symfony\\Component\\Ldap\\Ldap')] fn () => ($container->privates['Symfony\\Component\\Ldap\\Ldap'] ?? $container->load('getLdapService'))]));
    }
}
