<?php

namespace ContainerP6Dryyl;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAuthenticationService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Authentication\LegacyHandler\Authentication' shared autowired service.
     *
     * @return \App\Authentication\LegacyHandler\Authentication
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 3).'/core/backend/Authentication/LegacyHandler/Authentication.php';

        $a = ($container->privates['App\\Authentication\\LegacyHandler\\UserHandler'] ?? $container->load('getUserHandlerService'));

        if (isset($container->privates['App\\Authentication\\LegacyHandler\\Authentication'])) {
            return $container->privates['App\\Authentication\\LegacyHandler\\Authentication'];
        }

        return $container->privates['App\\Authentication\\LegacyHandler\\Authentication'] = new \App\Authentication\LegacyHandler\Authentication(\dirname(__DIR__, 3), (\dirname(__DIR__, 3).'/public/legacy'), 'SCRMSESSID', 'SCRMSESSID', ($container->privates['App\\Engine\\LegacyHandler\\LegacyScopeState'] ??= new \App\Engine\LegacyHandler\LegacyScopeState()), ($container->services['request_stack'] ??= new \Symfony\Component\HttpFoundation\RequestStack()), $container->parameters['system.settings'], $a);
    }
}
