<?php

namespace ContainerP6Dryyl;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAppListStringsStateProviderService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Languages\DataProvider\AppListStringsStateProvider' shared autowired service.
     *
     * @return \App\Languages\DataProvider\AppListStringsStateProvider
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 3).'/core/backend/Languages/DataProvider/AppListStringsStateProvider.php';

        return $container->privates['App\\Languages\\DataProvider\\AppListStringsStateProvider'] = new \App\Languages\DataProvider\AppListStringsStateProvider(($container->privates['App\\Languages\\LegacyHandler\\AppListStringsHandler'] ?? $container->load('getAppListStringsHandlerService')));
    }
}
