<?php

namespace ContainerP6Dryyl;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getArgumentResolver_ServiceService extends App_KernelProdContainer
{
    /*
     * Gets the private 'argument_resolver.service' shared service.
     *
     * @return \Symfony\Component\HttpKernel\Controller\ArgumentResolver\ServiceValueResolver
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 3).'/vendor/symfony/http-kernel/Controller/ArgumentValueResolverInterface.php';
        include_once \dirname(__DIR__, 3).'/vendor/symfony/http-kernel/Controller/ValueResolverInterface.php';
        include_once \dirname(__DIR__, 3).'/vendor/symfony/http-kernel/Controller/ArgumentResolver/ServiceValueResolver.php';

        return $container->privates['argument_resolver.service'] = new \Symfony\Component\HttpKernel\Controller\ArgumentResolver\ServiceValueResolver(new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'App\\Authentication\\Controller\\SecurityController::disable2fa' => ['privates', '.service_locator.PwPK5aK', 'get_ServiceLocator_PwPK5aKService', true],
            'App\\Authentication\\Controller\\SecurityController::enable2fa' => ['privates', '.service_locator.PwPK5aK', 'get_ServiceLocator_PwPK5aKService', true],
            'App\\Authentication\\Controller\\SecurityController::enableFinalize2fa' => ['privates', '.service_locator..bx6l6_', 'get_ServiceLocator__Bx6l6Service', true],
            'App\\Authentication\\Controller\\SecurityController::login' => ['privates', '.service_locator.PislOXO', 'get_ServiceLocator_PislOXOService', true],
            'App\\Authentication\\Controller\\SecurityController::nativeAuthLogin' => ['privates', '.service_locator.PislOXO', 'get_ServiceLocator_PislOXOService', true],
            'App\\Authentication\\Controller\\SecurityController::nativeAuthSessionStatus' => ['privates', '.service_locator.ATt7aga', 'get_ServiceLocator_ATt7agaService', true],
            'App\\Authentication\\Controller\\SecurityController::sessionStatus' => ['privates', '.service_locator.ATt7aga', 'get_ServiceLocator_ATt7agaService', true],
            'App\\Engine\\Controller\\IndexController::index' => ['privates', '.service_locator.ATt7aga', 'get_ServiceLocator_ATt7agaService', true],
            'App\\Engine\\Controller\\IndexController::loggedOut' => ['privates', '.service_locator.Q9_Ua5J', 'get_ServiceLocator_Q9Ua5JService', true],
            'App\\Engine\\Controller\\IndexController::nativeAuth' => ['privates', '.service_locator.ATt7aga', 'get_ServiceLocator_ATt7agaService', true],
            'Nbgrp\\OneloginSamlBundle\\Controller\\Login::__invoke' => ['privates', '.service_locator.zNgsiq9', 'get_ServiceLocator_ZNgsiq9Service', true],
            'Nbgrp\\OneloginSamlBundle\\Controller\\Metadata::__invoke' => ['privates', '.service_locator.zNgsiq9', 'get_ServiceLocator_ZNgsiq9Service', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Authentication\\Controller\\SecurityController:disable2fa' => ['privates', '.service_locator.PwPK5aK', 'get_ServiceLocator_PwPK5aKService', true],
            'App\\Authentication\\Controller\\SecurityController:enable2fa' => ['privates', '.service_locator.PwPK5aK', 'get_ServiceLocator_PwPK5aKService', true],
            'App\\Authentication\\Controller\\SecurityController:enableFinalize2fa' => ['privates', '.service_locator..bx6l6_', 'get_ServiceLocator__Bx6l6Service', true],
            'App\\Authentication\\Controller\\SecurityController:login' => ['privates', '.service_locator.PislOXO', 'get_ServiceLocator_PislOXOService', true],
            'App\\Authentication\\Controller\\SecurityController:nativeAuthLogin' => ['privates', '.service_locator.PislOXO', 'get_ServiceLocator_PislOXOService', true],
            'App\\Authentication\\Controller\\SecurityController:nativeAuthSessionStatus' => ['privates', '.service_locator.ATt7aga', 'get_ServiceLocator_ATt7agaService', true],
            'App\\Authentication\\Controller\\SecurityController:sessionStatus' => ['privates', '.service_locator.ATt7aga', 'get_ServiceLocator_ATt7agaService', true],
            'App\\Engine\\Controller\\IndexController:index' => ['privates', '.service_locator.ATt7aga', 'get_ServiceLocator_ATt7agaService', true],
            'App\\Engine\\Controller\\IndexController:loggedOut' => ['privates', '.service_locator.Q9_Ua5J', 'get_ServiceLocator_Q9Ua5JService', true],
            'App\\Engine\\Controller\\IndexController:nativeAuth' => ['privates', '.service_locator.ATt7aga', 'get_ServiceLocator_ATt7agaService', true],
            'Nbgrp\\OneloginSamlBundle\\Controller\\Login:__invoke' => ['privates', '.service_locator.zNgsiq9', 'get_ServiceLocator_ZNgsiq9Service', true],
            'Nbgrp\\OneloginSamlBundle\\Controller\\Login' => ['privates', '.service_locator.zNgsiq9', 'get_ServiceLocator_ZNgsiq9Service', true],
            'Nbgrp\\OneloginSamlBundle\\Controller\\Metadata:__invoke' => ['privates', '.service_locator.zNgsiq9', 'get_ServiceLocator_ZNgsiq9Service', true],
            'Nbgrp\\OneloginSamlBundle\\Controller\\Metadata' => ['privates', '.service_locator.zNgsiq9', 'get_ServiceLocator_ZNgsiq9Service', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
        ], [
            'App\\Authentication\\Controller\\SecurityController::disable2fa' => '?',
            'App\\Authentication\\Controller\\SecurityController::enable2fa' => '?',
            'App\\Authentication\\Controller\\SecurityController::enableFinalize2fa' => '?',
            'App\\Authentication\\Controller\\SecurityController::login' => '?',
            'App\\Authentication\\Controller\\SecurityController::nativeAuthLogin' => '?',
            'App\\Authentication\\Controller\\SecurityController::nativeAuthSessionStatus' => '?',
            'App\\Authentication\\Controller\\SecurityController::sessionStatus' => '?',
            'App\\Engine\\Controller\\IndexController::index' => '?',
            'App\\Engine\\Controller\\IndexController::loggedOut' => '?',
            'App\\Engine\\Controller\\IndexController::nativeAuth' => '?',
            'Nbgrp\\OneloginSamlBundle\\Controller\\Login::__invoke' => '?',
            'Nbgrp\\OneloginSamlBundle\\Controller\\Metadata::__invoke' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Authentication\\Controller\\SecurityController:disable2fa' => '?',
            'App\\Authentication\\Controller\\SecurityController:enable2fa' => '?',
            'App\\Authentication\\Controller\\SecurityController:enableFinalize2fa' => '?',
            'App\\Authentication\\Controller\\SecurityController:login' => '?',
            'App\\Authentication\\Controller\\SecurityController:nativeAuthLogin' => '?',
            'App\\Authentication\\Controller\\SecurityController:nativeAuthSessionStatus' => '?',
            'App\\Authentication\\Controller\\SecurityController:sessionStatus' => '?',
            'App\\Engine\\Controller\\IndexController:index' => '?',
            'App\\Engine\\Controller\\IndexController:loggedOut' => '?',
            'App\\Engine\\Controller\\IndexController:nativeAuth' => '?',
            'Nbgrp\\OneloginSamlBundle\\Controller\\Login:__invoke' => '?',
            'Nbgrp\\OneloginSamlBundle\\Controller\\Login' => '?',
            'Nbgrp\\OneloginSamlBundle\\Controller\\Metadata:__invoke' => '?',
            'Nbgrp\\OneloginSamlBundle\\Controller\\Metadata' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]));
    }
}
