<?php

namespace ContainerP6Dryyl;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getApiSuccessHandlerService extends App_KernelProdContainer
{
    /*
     * Gets the public 'api_success_handler' shared autowired service.
     *
     * @return \App\Security\TwoFactor\AuthenticationSuccessHandler
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 3).'/vendor/symfony/security-http/Authentication/AuthenticationSuccessHandlerInterface.php';
        include_once \dirname(__DIR__, 3).'/core/backend/Security/TwoFactor/AuthenticationSuccessHandler.php';

        return $container->services['api_success_handler'] = new \App\Security\TwoFactor\AuthenticationSuccessHandler();
    }
}
