<?php

namespace ContainerP6Dryyl;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getBaseLoggingEnvVarProcessorService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Logging\Services\BaseLoggingEnvVarProcessor' shared autowired service.
     *
     * @return \App\Logging\Services\BaseLoggingEnvVarProcessor
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 3).'/vendor/symfony/dependency-injection/EnvVarProcessorInterface.php';
        include_once \dirname(__DIR__, 3).'/core/backend/Logging/Services/BaseLoggingEnvVarProcessor.php';

        return $container->privates['App\\Logging\\Services\\BaseLoggingEnvVarProcessor'] = new \App\Logging\Services\BaseLoggingEnvVarProcessor(\dirname(__DIR__, 3));
    }
}
