<?php

namespace ContainerP6Dryyl;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getBatchedStatisticsStateProviderService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Statistics\DataProvider\BatchedStatisticsStateProvider' shared autowired service.
     *
     * @return \App\Statistics\DataProvider\BatchedStatisticsStateProvider
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 3).'/core/backend/Statistics/DataProvider/BatchedStatisticsStateProvider.php';

        return $container->privates['App\\Statistics\\DataProvider\\BatchedStatisticsStateProvider'] = new \App\Statistics\DataProvider\BatchedStatisticsStateProvider(($container->privates['App\\Statistics\\Service\\StatisticsManager'] ?? $container->load('getStatisticsManagerService')));
    }
}
