<?php

namespace ContainerP6Dryyl;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCacheManagerHandlerService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Engine\LegacyHandler\CacheManagerHandler' shared autowired service.
     *
     * @return \App\Engine\LegacyHandler\CacheManagerHandler
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 3).'/core/backend/Engine/Service/CacheManagerInterface.php';
        include_once \dirname(__DIR__, 3).'/core/backend/Engine/LegacyHandler/CacheManagerHandler.php';

        $a = ($container->services['cache.app'] ?? $container->load('getCache_AppService'));

        return $container->privates['App\\Engine\\LegacyHandler\\CacheManagerHandler'] = new \App\Engine\LegacyHandler\CacheManagerHandler(\dirname(__DIR__, 3), (\dirname(__DIR__, 3).'/public/legacy'), 'SCRMSESSID', 'SCRMSESSID', ($container->privates['App\\Engine\\LegacyHandler\\LegacyScopeState'] ??= new \App\Engine\LegacyHandler\LegacyScopeState()), ($container->services['request_stack'] ??= new \Symfony\Component\HttpFoundation\RequestStack()), $a, $a);
    }
}
