<?php

namespace ContainerP6Dryyl;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDateFieldDefaultCalculationService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Process\Service\FieldDefault\DateFieldDefaultCalculation' shared autowired service.
     *
     * @return \App\Process\Service\FieldDefault\DateFieldDefaultCalculation
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 3).'/core/backend/Process/Service/ProcessHandlerInterface.php';
        include_once \dirname(__DIR__, 3).'/core/backend/Process/Service/FieldDefault/DateFieldDefaultCalculation.php';

        return $container->privates['App\\Process\\Service\\FieldDefault\\DateFieldDefaultCalculation'] = new \App\Process\Service\FieldDefault\DateFieldDefaultCalculation(\dirname(__DIR__, 3), (\dirname(__DIR__, 3).'/public/legacy'), 'SCRMSESSID', 'SCRMSESSID', ($container->privates['App\\Engine\\LegacyHandler\\LegacyScopeState'] ??= new \App\Engine\LegacyHandler\LegacyScopeState()), ($container->services['request_stack'] ??= new \Symfony\Component\HttpFoundation\RequestStack()));
    }
}
