<?php

namespace ContainerP6Dryyl;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEntityRecordMapperRunnerService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Data\Service\Record\EntityRecordMappers\EntityRecordMapperRunner' shared autowired service.
     *
     * @return \App\Data\Service\Record\EntityRecordMappers\EntityRecordMapperRunner
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 3).'/core/backend/Data/Service/Record/Mappers/RecordMapperRunnerInterface.php';
        include_once \dirname(__DIR__, 3).'/core/backend/Data/Service/Record/Mappers/RecordMapperRunner.php';
        include_once \dirname(__DIR__, 3).'/core/backend/Data/Service/Record/EntityRecordMappers/EntityRecordMapperRunner.php';
        include_once \dirname(__DIR__, 3).'/core/backend/Data/Service/Record/Mappers/ModuleMapperTrait.php';
        include_once \dirname(__DIR__, 3).'/core/backend/Data/Service/Record/Mappers/RecordFieldMapperTrait.php';
        include_once \dirname(__DIR__, 3).'/core/backend/Data/Service/Record/Mappers/BaseFieldMapperRegistry.php';
        include_once \dirname(__DIR__, 3).'/core/backend/Data/Service/Record/Mappers/BaseFieldMapperRegistryFactory.php';
        include_once \dirname(__DIR__, 3).'/core/backend/Data/Service/Record/Mappers/BaseFieldTypeMapperRegistry.php';
        include_once \dirname(__DIR__, 3).'/core/backend/Data/Service/Record/Mappers/BaseFieldTypeMapperRegistryFactory.php';
        include_once \dirname(__DIR__, 3).'/core/backend/Data/Service/Record/Mappers/RecordMapperTrait.php';
        include_once \dirname(__DIR__, 3).'/core/backend/Data/Service/Record/Mappers/BaseRecordMapperRegistry.php';
        include_once \dirname(__DIR__, 3).'/core/backend/Data/Service/Record/Mappers/BaseRecordMapperRegistryFactory.php';

        return $container->privates['App\\Data\\Service\\Record\\EntityRecordMappers\\EntityRecordMapperRunner'] = new \App\Data\Service\Record\EntityRecordMappers\EntityRecordMapperRunner(\App\Data\Service\Record\Mappers\BaseFieldMapperRegistryFactory::create(new RewindableGenerator(fn () => new \EmptyIterator(), 0)), \App\Data\Service\Record\Mappers\BaseFieldTypeMapperRegistryFactory::create(new RewindableGenerator(fn () => new \EmptyIterator(), 0)), \App\Data\Service\Record\Mappers\BaseRecordMapperRegistryFactory::create(new RewindableGenerator(fn () => new \EmptyIterator(), 0)), ($container->privates['App\\FieldDefinitions\\LegacyHandler\\FieldDefinitionsHandler'] ?? $container->load('getFieldDefinitionsHandlerService')));
    }
}
