<?php

namespace ContainerP6Dryyl;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getExtensionAssetCopyCacheWarmerService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Engine\Service\Extensions\ExtensionAssetCopyCacheWarmer' shared autowired service.
     *
     * @return \App\Engine\Service\Extensions\ExtensionAssetCopyCacheWarmer
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 3).'/vendor/symfony/http-kernel/CacheWarmer/CacheWarmerInterface.php';
        include_once \dirname(__DIR__, 3).'/core/backend/Engine/Service/Extensions/ExtensionAssetCopyCacheWarmer.php';
        include_once \dirname(__DIR__, 3).'/core/backend/Engine/Service/Extensions/ExtensionAssetCopyInterface.php';
        include_once \dirname(__DIR__, 3).'/core/backend/Engine/Service/Extensions/ExtensionAssetCopy.php';

        return $container->privates['App\\Engine\\Service\\Extensions\\ExtensionAssetCopyCacheWarmer'] = new \App\Engine\Service\Extensions\ExtensionAssetCopyCacheWarmer(($container->privates['App\\Engine\\Service\\Extensions\\ExtensionAssetCopy'] ??= new \App\Engine\Service\Extensions\ExtensionAssetCopy(\dirname(__DIR__, 3))));
    }
}
