<?php

namespace ContainerP6Dryyl;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getGenerateBackupCodesHandlerService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Process\LegacyHandler\GenerateBackupCodesHandler' shared autowired service.
     *
     * @return \App\Process\LegacyHandler\GenerateBackupCodesHandler
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 3).'/core/backend/Process/Service/ProcessHandlerInterface.php';
        include_once \dirname(__DIR__, 3).'/core/backend/Process/LegacyHandler/GenerateBackupCodesHandler.php';
        include_once \dirname(__DIR__, 3).'/core/backend/Security/TwoFactor/BackupCodeGenerator.php';

        $a = ($container->privates['security.helper'] ?? $container->load('getSecurity_HelperService'));

        if (isset($container->privates['App\\Process\\LegacyHandler\\GenerateBackupCodesHandler'])) {
            return $container->privates['App\\Process\\LegacyHandler\\GenerateBackupCodesHandler'];
        }

        return $container->privates['App\\Process\\LegacyHandler\\GenerateBackupCodesHandler'] = new \App\Process\LegacyHandler\GenerateBackupCodesHandler(\dirname(__DIR__, 3), (\dirname(__DIR__, 3).'/public/legacy'), 'SCRMSESSID', 'SCRMSESSID', ($container->privates['App\\Engine\\LegacyHandler\\LegacyScopeState'] ??= new \App\Engine\LegacyHandler\LegacyScopeState()), ($container->services['request_stack'] ??= new \Symfony\Component\HttpFoundation\RequestStack()), $a, new \App\Security\TwoFactor\BackupCodeGenerator(), ($container->privates['App\\Data\\LegacyHandler\\PreparedStatementHandler'] ?? $container->load('getPreparedStatementHandlerService')));
    }
}
