<?php

namespace ContainerP6Dryyl;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getIndexControllerService extends App_KernelProdContainer
{
    /*
     * Gets the public 'App\Engine\Controller\IndexController' shared autowired service.
     *
     * @return \App\Engine\Controller\IndexController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 3).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 3).'/core/backend/Engine/Controller/IndexController.php';

        $container->services['App\\Engine\\Controller\\IndexController'] = $instance = new \App\Engine\Controller\IndexController(\dirname(__DIR__, 3), 'SCRMSESSID', 'SCRMSESSID', ($container->privates['App\\Authentication\\LegacyHandler\\UserHandler'] ?? $container->load('getUserHandlerService')), ($container->privates['App\\Authentication\\LegacyHandler\\Authentication'] ?? $container->load('getAuthenticationService')));

        $instance->setContainer(($container->privates['.service_locator.O1Dz4k_'] ?? $container->load('get_ServiceLocator_O1Dz4kService'))->withContext('App\\Engine\\Controller\\IndexController', $container));

        return $instance;
    }
}
