<?php

namespace ContainerP6Dryyl;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getInstallHandlerService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Install\LegacyHandler\InstallHandler' shared autowired service.
     *
     * @return \App\Install\LegacyHandler\InstallHandler
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 3).'/core/backend/Install/LegacyHandler/InstallHandler.php';
        include_once \dirname(__DIR__, 3).'/core/backend/Security/AppSecretGenerator.php';

        return $container->privates['App\\Install\\LegacyHandler\\InstallHandler'] = new \App\Install\LegacyHandler\InstallHandler(\dirname(__DIR__, 3), (\dirname(__DIR__, 3).'/public/legacy'), 'SCRMSESSID', 'SCRMSESSID', ($container->privates['App\\Engine\\LegacyHandler\\LegacyScopeState'] ??= new \App\Engine\LegacyHandler\LegacyScopeState()), ($container->services['request_stack'] ??= new \Symfony\Component\HttpFoundation\RequestStack()), ($container->privates['monolog.logger'] ?? self::getMonolog_LoggerService($container)), ($container->services['security.app_secret_generator'] ??= new \App\Security\AppSecretGenerator()));
    }
}
