<?php

namespace ContainerP6Dryyl;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLoginSuccessEventListenerService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Security\LoginSuccessEventListener' shared autowired service.
     *
     * @return \App\Security\LoginSuccessEventListener
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 3).'/core/backend/Security/LoginSuccessEventListener.php';

        $a = ($container->privates['App\\Authentication\\LegacyHandler\\Authentication'] ?? $container->load('getAuthenticationService'));

        if (isset($container->privates['App\\Security\\LoginSuccessEventListener'])) {
            return $container->privates['App\\Security\\LoginSuccessEventListener'];
        }

        return $container->privates['App\\Security\\LoginSuccessEventListener'] = new \App\Security\LoginSuccessEventListener($a, ($container->services['app.system-configs'] ?? $container->load('getApp_SystemconfigsService')));
    }
}
