<?php

namespace ContainerP6Dryyl;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLineItemsSaveHandlerService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Module\Service\Fields\LineItems\SaveHandlers\LineItemsSaveHandler' shared autowired service.
     *
     * @return \App\Module\Service\Fields\LineItems\SaveHandlers\LineItemsSaveHandler
     */
    public static function do($container, $lazyLoad = true)
    {
        if (true === $lazyLoad) {
            return $container->privates['App\\Module\\Service\\Fields\\LineItems\\SaveHandlers\\LineItemsSaveHandler'] = $container->createProxy('LineItemsSaveHandlerGhostFcf7cbf', static fn () => \LineItemsSaveHandlerGhostFcf7cbf::createLazyGhost(static fn ($proxy) => self::do($container, $proxy)));
        }

        include_once \dirname(__DIR__, 3).'/core/backend/Data/Service/Record/RecordSaveHandlers/BaseModuleSaveHandlerInterface.php';
        include_once \dirname(__DIR__, 3).'/core/backend/Data/Service/Record/RecordSaveHandlers/RecordFieldTypeSaveHandlerInterface.php';
        include_once \dirname(__DIR__, 3).'/core/backend/Module/Service/Fields/LineItems/SaveHandlers/LineItemsSaveHandler.php';

        return ($lazyLoad->__construct(($container->privates['App\\Data\\LegacyHandler\\LinkedRecords\\LinkedRecordsProvider'] ?? $container->load('getLinkedRecordsProviderService'))) && false ?: $lazyLoad);
    }
}
