<?php

namespace ContainerP6Dryyl;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLinkedRecordsProviderService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Data\LegacyHandler\LinkedRecords\LinkedRecordsProvider' shared autowired service.
     *
     * @return \App\Data\LegacyHandler\LinkedRecords\LinkedRecordsProvider
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 3).'/core/backend/Data/Service/LinkedRecords/LinkedRecordsProviderInterface.php';
        include_once \dirname(__DIR__, 3).'/core/backend/Data/LegacyHandler/LinkedRecords/LinkedRecordsProvider.php';

        $a = ($container->privates['App\\Data\\LegacyHandler\\RecordHandler'] ?? $container->load('getRecordHandlerService'));

        if (isset($container->privates['App\\Data\\LegacyHandler\\LinkedRecords\\LinkedRecordsProvider'])) {
            return $container->privates['App\\Data\\LegacyHandler\\LinkedRecords\\LinkedRecordsProvider'];
        }

        return $container->privates['App\\Data\\LegacyHandler\\LinkedRecords\\LinkedRecordsProvider'] = new \App\Data\LegacyHandler\LinkedRecords\LinkedRecordsProvider(\dirname(__DIR__, 3), (\dirname(__DIR__, 3).'/public/legacy'), 'SCRMSESSID', 'SCRMSESSID', ($container->privates['App\\Engine\\LegacyHandler\\LegacyScopeState'] ??= new \App\Engine\LegacyHandler\LegacyScopeState()), ($container->services['request_stack'] ??= new \Symfony\Component\HttpFoundation\RequestStack()), ($container->privates['App\\Module\\LegacyHandler\\ModuleNameMapperHandler'] ?? self::getModuleNameMapperHandlerService($container)), ($container->privates['App\\FieldDefinitions\\LegacyHandler\\FieldDefinitionsHandler'] ?? $container->load('getFieldDefinitionsHandlerService')), $a, ($container->privates['App\\Data\\LegacyHandler\\RecordDeletionHandler'] ?? $container->load('getRecordDeletionHandlerService')));
    }
}
