<?php

namespace ContainerP6Dryyl;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLegacySessionLogoutListenerService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Security\LegacySessionLogoutListener' shared autowired service.
     *
     * @return \App\Security\LegacySessionLogoutListener
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 3).'/core/backend/Security/LegacySessionLogoutListener.php';

        $a = ($container->privates['App\\Authentication\\LegacyHandler\\Authentication'] ?? $container->load('getAuthenticationService'));

        if (isset($container->privates['App\\Security\\LegacySessionLogoutListener'])) {
            return $container->privates['App\\Security\\LegacySessionLogoutListener'];
        }

        return $container->privates['App\\Security\\LegacySessionLogoutListener'] = new \App\Security\LegacySessionLogoutListener($a);
    }
}
