<?php

namespace ContainerP6Dryyl;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLineItemsRetrieveApiMapperService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Module\Service\Fields\LineItems\Mappers\LineItemsRetrieveApiMapper' shared autowired service.
     *
     * @return \App\Module\Service\Fields\LineItems\Mappers\LineItemsRetrieveApiMapper
     */
    public static function do($container, $lazyLoad = true)
    {
        if (true === $lazyLoad) {
            return $container->privates['App\\Module\\Service\\Fields\\LineItems\\Mappers\\LineItemsRetrieveApiMapper'] = $container->createProxy('LineItemsRetrieveApiMapperGhost80d1d1e', static fn () => \LineItemsRetrieveApiMapperGhost80d1d1e::createLazyGhost(static fn ($proxy) => self::do($container, $proxy)));
        }

        include_once \dirname(__DIR__, 3).'/core/backend/Data/Service/Record/Mappers/BaseModuleMapperInterface.php';
        include_once \dirname(__DIR__, 3).'/core/backend/Data/Service/Record/Mappers/BaseFieldTypeMapperInterface.php';
        include_once \dirname(__DIR__, 3).'/core/backend/Data/Service/Record/ApiRecordMappers/ApiRecordFieldTypeMapperInterface.php';
        include_once \dirname(__DIR__, 3).'/core/backend/Module/Service/Fields/LineItems/Mappers/LineItemsApiMapperTrait.php';
        include_once \dirname(__DIR__, 3).'/core/backend/Module/Service/Fields/LineItems/Mappers/LineItemsRetrieveApiMapper.php';

        return ($lazyLoad->__construct(($container->privates['App\\Data\\LegacyHandler\\LinkedRecords\\LinkedRecordsProvider'] ?? $container->load('getLinkedRecordsProviderService'))) && false ?: $lazyLoad);
    }
}
