<?php

namespace ContainerP6Dryyl;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLdapService extends App_KernelProdContainer
{
    /*
     * Gets the private 'Symfony\Component\Ldap\Ldap' shared service.
     *
     * @return \Symfony\Component\Ldap\Ldap
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 3).'/vendor/symfony/ldap/LdapInterface.php';
        include_once \dirname(__DIR__, 3).'/vendor/symfony/ldap/Ldap.php';
        include_once \dirname(__DIR__, 3).'/vendor/symfony/ldap/Adapter/AdapterInterface.php';
        include_once \dirname(__DIR__, 3).'/vendor/symfony/ldap/Adapter/ExtLdap/Adapter.php';

        return $container->privates['Symfony\\Component\\Ldap\\Ldap'] = new \Symfony\Component\Ldap\Ldap(new \Symfony\Component\Ldap\Adapter\ExtLdap\Adapter($container->parameters['ldap.options']));
    }
}
