<?php

namespace ContainerP6Dryyl;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMonolog_Logger_UpgradeService extends App_KernelProdContainer
{
    /*
     * Gets the public 'monolog.logger.upgrade' shared service.
     *
     * @return \Monolog\Logger
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['monolog.logger.upgrade'] = $instance = new \Monolog\Logger('upgrade');

        $instance->pushHandler(($container->privates['monolog.handler.upgrade'] ?? $container->load('getMonolog_Handler_UpgradeService')));

        return $instance;
    }
}
