<?php

namespace ContainerP6Dryyl;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getModStringsHandlerService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Languages\LegacyHandler\ModStringsHandler' shared autowired service.
     *
     * @return \App\Languages\LegacyHandler\ModStringsHandler
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 3).'/core/backend/Languages/LegacyHandler/ModStringsHandler.php';

        return $container->privates['App\\Languages\\LegacyHandler\\ModStringsHandler'] = new \App\Languages\LegacyHandler\ModStringsHandler(\dirname(__DIR__, 3), (\dirname(__DIR__, 3).'/public/legacy'), 'SCRMSESSID', 'SCRMSESSID', ($container->privates['App\\Engine\\LegacyHandler\\LegacyScopeState'] ??= new \App\Engine\LegacyHandler\LegacyScopeState()), ($container->privates['App\\Module\\LegacyHandler\\ModuleNameMapperHandler'] ?? self::getModuleNameMapperHandlerService($container)), ($container->privates['App\\Module\\LegacyHandler\\ModuleRegistryHandler'] ?? $container->load('getModuleRegistryHandlerService')), ($container->services['request_stack'] ??= new \Symfony\Component\HttpFoundation\RequestStack()), []);
    }
}
