<?php

namespace ContainerP6Dryyl;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMigrationFactoryDecoratorService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Install\Service\Migrations\MigrationFactoryDecorator' shared autowired service.
     *
     * @return \App\Install\Service\Migrations\MigrationFactoryDecorator
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 3).'/vendor/doctrine/migrations/lib/Doctrine/Migrations/Version/MigrationFactory.php';
        include_once \dirname(__DIR__, 3).'/core/backend/Install/Service/Migrations/MigrationFactoryDecorator.php';
        include_once \dirname(__DIR__, 3).'/vendor/doctrine/migrations/lib/Doctrine/Migrations/Version/DbalMigrationFactory.php';

        return $container->privates['App\\Install\\Service\\Migrations\\MigrationFactoryDecorator'] = new \App\Install\Service\Migrations\MigrationFactoryDecorator(new \Doctrine\Migrations\Version\DbalMigrationFactory(($container->services['doctrine.dbal.default_connection'] ?? self::getDoctrine_Dbal_DefaultConnectionService($container)), ($container->privates['monolog.logger'] ?? self::getMonolog_LoggerService($container))), $container);
    }
}
