<?php

namespace ContainerP6Dryyl;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getModuleMetadataStateProviderService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Metadata\DataProvider\ModuleMetadataStateProvider' shared autowired service.
     *
     * @return \App\Metadata\DataProvider\ModuleMetadataStateProvider
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 3).'/core/backend/Metadata/DataProvider/ModuleMetadataStateProvider.php';

        $a = ($container->privates['App\\Metadata\\Service\\ModuleMetadataProvider'] ?? $container->load('getModuleMetadataProviderService'));

        if (isset($container->privates['App\\Metadata\\DataProvider\\ModuleMetadataStateProvider'])) {
            return $container->privates['App\\Metadata\\DataProvider\\ModuleMetadataStateProvider'];
        }

        return $container->privates['App\\Metadata\\DataProvider\\ModuleMetadataStateProvider'] = new \App\Metadata\DataProvider\ModuleMetadataStateProvider($a);
    }
}
