<?php

namespace ContainerP6Dryyl;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getModStringsStateProviderService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Languages\DataProvider\ModStringsStateProvider' shared autowired service.
     *
     * @return \App\Languages\DataProvider\ModStringsStateProvider
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 3).'/core/backend/Languages/DataProvider/ModStringsStateProvider.php';

        return $container->privates['App\\Languages\\DataProvider\\ModStringsStateProvider'] = new \App\Languages\DataProvider\ModStringsStateProvider(($container->privates['App\\Languages\\LegacyHandler\\ModStringsHandler'] ?? $container->load('getModStringsHandlerService')));
    }
}
