<?php

namespace ContainerP6Dryyl;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getNavbarStateProviderService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Navbar\DataProvider\NavbarStateProvider' shared autowired service.
     *
     * @return \App\Navbar\DataProvider\NavbarStateProvider
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 3).'/core/backend/Navbar/DataProvider/NavbarStateProvider.php';

        $a = ($container->privates['security.helper'] ?? $container->load('getSecurity_HelperService'));

        if (isset($container->privates['App\\Navbar\\DataProvider\\NavbarStateProvider'])) {
            return $container->privates['App\\Navbar\\DataProvider\\NavbarStateProvider'];
        }

        return $container->privates['App\\Navbar\\DataProvider\\NavbarStateProvider'] = new \App\Navbar\DataProvider\NavbarStateProvider(($container->privates['App\\Navbar\\LegacyHandler\\NavbarHandler'] ?? $container->load('getNavbarHandlerService')), $a);
    }
}
