<?php

namespace ContainerP6Dryyl;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getProcessStateProviderService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Process\DataProvider\ProcessStateProvider' shared autowired service.
     *
     * @return \App\Process\DataProvider\ProcessStateProvider
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 3).'/core/backend/Process/DataProvider/ProcessStateProvider.php';

        return $container->privates['App\\Process\\DataProvider\\ProcessStateProvider'] = new \App\Process\DataProvider\ProcessStateProvider();
    }
}
