<?php

namespace ContainerP6Dryyl;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSystemConfigStateProviderService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\SystemConfig\DataProvider\SystemConfigStateProvider' shared autowired service.
     *
     * @return \App\SystemConfig\DataProvider\SystemConfigStateProvider
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 3).'/core/backend/SystemConfig/DataProvider/SystemConfigStateProvider.php';

        return $container->privates['App\\SystemConfig\\DataProvider\\SystemConfigStateProvider'] = new \App\SystemConfig\DataProvider\SystemConfigStateProvider(($container->services['app.system-configs'] ?? $container->load('getApp_SystemconfigsService')));
    }
}
