<?php

namespace ContainerP6Dryyl;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSecurityControllerService extends App_KernelProdContainer
{
    /*
     * Gets the public 'App\Authentication\Controller\SecurityController' shared autowired service.
     *
     * @return \App\Authentication\Controller\SecurityController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 3).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 3).'/core/backend/Authentication/Controller/SecurityController.php';

        $container->services['App\\Authentication\\Controller\\SecurityController'] = $instance = new \App\Authentication\Controller\SecurityController(($container->privates['App\\Authentication\\LegacyHandler\\Authentication'] ?? $container->load('getAuthenticationService')), ($container->services['request_stack'] ??= new \Symfony\Component\HttpFoundation\RequestStack()), ($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container)), ($container->privates['App\\Data\\LegacyHandler\\PreparedStatementHandler'] ?? $container->load('getPreparedStatementHandlerService')), ($container->privates['App\\Authentication\\LegacyHandler\\UserHandler'] ?? $container->load('getUserHandlerService')), ($container->privates['App\\Engine\\LegacyHandler\\CacheManagerHandler'] ?? $container->load('getCacheManagerHandlerService')));

        $instance->setContainer(($container->privates['.service_locator.O1Dz4k_'] ?? $container->load('get_ServiceLocator_O1Dz4kService'))->withContext('App\\Authentication\\Controller\\SecurityController', $container));

        return $instance;
    }
}
