<?php

namespace ContainerP6Dryyl;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSchebTwoFactor_Security_Totp_ProviderService extends App_KernelProdContainer
{
    /*
     * Gets the private 'scheb_two_factor.security.totp.provider' shared service.
     *
     * @return \Scheb\TwoFactorBundle\Security\TwoFactor\Provider\Totp\TotpAuthenticatorTwoFactorProvider
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 3).'/vendor/scheb/2fa-bundle/Security/TwoFactor/Provider/TwoFactorProviderInterface.php';
        include_once \dirname(__DIR__, 3).'/vendor/scheb/2fa-totp/Security/TwoFactor/Provider/Totp/TotpAuthenticatorTwoFactorProvider.php';

        $a = ($container->privates['scheb_two_factor.security.totp.default_form_renderer'] ?? $container->load('getSchebTwoFactor_Security_Totp_DefaultFormRendererService'));

        if (isset($container->privates['scheb_two_factor.security.totp.provider'])) {
            return $container->privates['scheb_two_factor.security.totp.provider'];
        }

        return $container->privates['scheb_two_factor.security.totp.provider'] = new \Scheb\TwoFactorBundle\Security\TwoFactor\Provider\Totp\TotpAuthenticatorTwoFactorProvider(($container->services['scheb_two_factor.security.totp_authenticator'] ?? $container->load('getSchebTwoFactor_Security_TotpAuthenticatorService')), $a);
    }
}
