<?php

namespace ContainerP6Dryyl;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSecurity_PasswordHasherFactoryService extends App_KernelProdContainer
{
    /*
     * Gets the private 'security.password_hasher_factory' shared service.
     *
     * @return \Symfony\Component\PasswordHasher\Hasher\PasswordHasherFactory
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 3).'/vendor/symfony/password-hasher/Hasher/PasswordHasherFactoryInterface.php';
        include_once \dirname(__DIR__, 3).'/vendor/symfony/password-hasher/Hasher/PasswordHasherFactory.php';
        include_once \dirname(__DIR__, 3).'/vendor/symfony/password-hasher/PasswordHasherInterface.php';
        include_once \dirname(__DIR__, 3).'/vendor/symfony/password-hasher/Hasher/CheckPasswordLengthTrait.php';
        include_once \dirname(__DIR__, 3).'/core/backend/Security/LegacyPasswordHasher.php';

        $a = new \App\Security\LegacyPasswordHasher();

        return $container->privates['security.password_hasher_factory'] = new \Symfony\Component\PasswordHasher\Hasher\PasswordHasherFactory(['App\\Module\\Users\\Entity\\User' => $a, 'app_hasher' => $a]);
    }
}
