<?php

namespace ContainerP6Dryyl;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSchebTwoFactor_Security_Totp_DefaultFormRendererService extends App_KernelProdContainer
{
    /*
     * Gets the private 'scheb_two_factor.security.totp.default_form_renderer' shared service.
     *
     * @return \Scheb\TwoFactorBundle\Security\TwoFactor\Provider\DefaultTwoFactorFormRenderer
     */
    public static function do($container, $lazyLoad = true)
    {
        if (true === $lazyLoad) {
            return $container->privates['scheb_two_factor.security.totp.default_form_renderer'] = $container->createProxy('DefaultTwoFactorFormRendererGhostF0145ff', static fn () => \DefaultTwoFactorFormRendererGhostF0145ff::createLazyGhost(static fn ($proxy) => self::do($container, $proxy)));
        }

        include_once \dirname(__DIR__, 3).'/vendor/scheb/2fa-bundle/Security/TwoFactor/Provider/TwoFactorFormRendererInterface.php';
        include_once \dirname(__DIR__, 3).'/vendor/scheb/2fa-bundle/Security/TwoFactor/Provider/DefaultTwoFactorFormRenderer.php';

        return ($lazyLoad->__construct(($container->privates['twig'] ?? $container->load('getTwigService')), '@SchebTwoFactor/Authentication/form.html.twig') && false ?: $lazyLoad);
    }
}
