<?php

namespace ContainerP6Dryyl;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSamlLogoutListenerService extends App_KernelProdContainer
{
    /*
     * Gets the private 'Nbgrp\OneloginSamlBundle\EventListener\Security\SamlLogoutListener' shared service.
     *
     * @return \Nbgrp\OneloginSamlBundle\EventListener\Security\SamlLogoutListener
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 3).'/vendor/nbgrp/onelogin-saml-bundle/src/EventListener/Security/SamlLogoutListener.php';
        include_once \dirname(__DIR__, 3).'/vendor/nbgrp/onelogin-saml-bundle/src/Idp/IdpResolverInterface.php';
        include_once \dirname(__DIR__, 3).'/vendor/nbgrp/onelogin-saml-bundle/src/Idp/IdpResolver.php';

        return $container->privates['Nbgrp\\OneloginSamlBundle\\EventListener\\Security\\SamlLogoutListener'] = new \Nbgrp\OneloginSamlBundle\EventListener\Security\SamlLogoutListener(($container->privates['Nbgrp\\OneloginSamlBundle\\Onelogin\\AuthRegistryInterface'] ?? $container->load('getAuthRegistryInterfaceService')), ($container->privates['Nbgrp\\OneloginSamlBundle\\Idp\\IdpResolverInterface'] ??= new \Nbgrp\OneloginSamlBundle\Idp\IdpResolver('idp')));
    }
}
