<?php

namespace ContainerP6Dryyl;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSchebTwoFactor_Security_TotpFactoryService extends App_KernelProdContainer
{
    /*
     * Gets the public 'scheb_two_factor.security.totp_factory' shared service.
     *
     * @return \Scheb\TwoFactorBundle\Security\TwoFactor\Provider\Totp\TotpFactory
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 3).'/vendor/scheb/2fa-totp/Security/TwoFactor/Provider/Totp/TotpFactory.php';

        return $container->services['scheb_two_factor.security.totp_factory'] = new \Scheb\TwoFactorBundle\Security\TwoFactor\Provider\Totp\TotpFactory('SuiteCRM', 'SuiteCRM', []);
    }
}
