<?php

namespace ContainerP6Dryyl;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTotpPreferenceMapperService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\UserPreferences\LegacyHandler\Mappers\TotpPreferenceMapper' shared autowired service.
     *
     * @return \App\UserPreferences\LegacyHandler\Mappers\TotpPreferenceMapper
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 3).'/core/backend/UserPreferences/LegacyHandler/UserPreferencesMapperInterface.php';
        include_once \dirname(__DIR__, 3).'/core/backend/UserPreferences/LegacyHandler/Mappers/TotpPreferenceMapper.php';

        $a = ($container->privates['security.helper'] ?? $container->load('getSecurity_HelperService'));

        if (isset($container->privates['App\\UserPreferences\\LegacyHandler\\Mappers\\TotpPreferenceMapper'])) {
            return $container->privates['App\\UserPreferences\\LegacyHandler\\Mappers\\TotpPreferenceMapper'];
        }

        return $container->privates['App\\UserPreferences\\LegacyHandler\\Mappers\\TotpPreferenceMapper'] = new \App\UserPreferences\LegacyHandler\Mappers\TotpPreferenceMapper($a);
    }
}
