<?php

namespace ContainerP6Dryyl;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTotpEncryptionListenerService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Security\TwoFactor\EventListener\TotpEncryptionListener' shared autowired service.
     *
     * @return \App\Security\TwoFactor\EventListener\TotpEncryptionListener
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 3).'/core/backend/Security/TwoFactor/EventListener/TotpEncryptionListener.php';
        include_once \dirname(__DIR__, 3).'/core/backend/Security/TwoFactor/LegacyHandler/BlowfishCodeHandler.php';

        return $container->privates['App\\Security\\TwoFactor\\EventListener\\TotpEncryptionListener'] = new \App\Security\TwoFactor\EventListener\TotpEncryptionListener(new \App\Security\TwoFactor\LegacyHandler\BlowfishCodeHandler(\dirname(__DIR__, 3), (\dirname(__DIR__, 3).'/public/legacy'), 'SCRMSESSID', 'SCRMSESSID', ($container->privates['App\\Engine\\LegacyHandler\\LegacyScopeState'] ??= new \App\Engine\LegacyHandler\LegacyScopeState()), ($container->services['request_stack'] ??= new \Symfony\Component\HttpFoundation\RequestStack())));
    }
}
