<?php

namespace ContainerP6Dryyl;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUserService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Module\Users\Entity\User' shared autowired service.
     *
     * @return \App\Module\Users\Entity\User
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 3).'/vendor/symfony/security-core/User/UserInterface.php';
        include_once \dirname(__DIR__, 3).'/vendor/symfony/security-core/User/EquatableInterface.php';
        include_once \dirname(__DIR__, 3).'/vendor/symfony/security-core/User/PasswordAuthenticatedUserInterface.php';
        include_once \dirname(__DIR__, 3).'/vendor/scheb/2fa-totp/Model/Totp/TwoFactorInterface.php';
        include_once \dirname(__DIR__, 3).'/vendor/scheb/2fa-backup-code/Model/BackupCodeInterface.php';
        include_once \dirname(__DIR__, 3).'/core/modules/Users/Entity/User.php';

        return $container->privates['App\\Module\\Users\\Entity\\User'] = new \App\Module\Users\Entity\User();
    }
}
