<?php

namespace ContainerP6Dryyl;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUserHandlerService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Authentication\LegacyHandler\UserHandler' shared autowired service.
     *
     * @return \App\Authentication\LegacyHandler\UserHandler
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 3).'/core/backend/Authentication/LegacyHandler/UserHandler.php';

        $a = ($container->privates['App\\UserPreferences\\LegacyHandler\\UserPreferenceHandler'] ?? $container->load('getUserPreferenceHandlerService'));

        if (isset($container->privates['App\\Authentication\\LegacyHandler\\UserHandler'])) {
            return $container->privates['App\\Authentication\\LegacyHandler\\UserHandler'];
        }

        return $container->privates['App\\Authentication\\LegacyHandler\\UserHandler'] = new \App\Authentication\LegacyHandler\UserHandler(\dirname(__DIR__, 3), (\dirname(__DIR__, 3).'/public/legacy'), 'SCRMSESSID', 'SCRMSESSID', ($container->privates['App\\Engine\\LegacyHandler\\LegacyScopeState'] ??= new \App\Engine\LegacyHandler\LegacyScopeState()), ($container->services['request_stack'] ??= new \Symfony\Component\HttpFoundation\RequestStack()), ($container->services['app.system-configs'] ?? $container->load('getApp_SystemconfigsService')), $a);
    }
}
