<?php

namespace ContainerP6Dryyl;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUserPreferenceStateProviderService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\UserPreferences\DataProvider\UserPreferenceStateProvider' shared autowired service.
     *
     * @return \App\UserPreferences\DataProvider\UserPreferenceStateProvider
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 3).'/core/backend/UserPreferences/DataProvider/UserPreferenceStateProvider.php';

        $a = ($container->privates['App\\UserPreferences\\LegacyHandler\\UserPreferenceHandler'] ?? $container->load('getUserPreferenceHandlerService'));

        if (isset($container->privates['App\\UserPreferences\\DataProvider\\UserPreferenceStateProvider'])) {
            return $container->privates['App\\UserPreferences\\DataProvider\\UserPreferenceStateProvider'];
        }

        return $container->privates['App\\UserPreferences\\DataProvider\\UserPreferenceStateProvider'] = new \App\UserPreferences\DataProvider\UserPreferenceStateProvider($a);
    }
}
