<?php

namespace ContainerP6Dryyl;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getViewDefinitionStateProviderService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\ViewDefinitions\DataProvider\ViewDefinitionStateProvider' shared autowired service.
     *
     * @return \App\ViewDefinitions\DataProvider\ViewDefinitionStateProvider
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 3).'/core/backend/ViewDefinitions/DataProvider/ViewDefinitionStateProvider.php';

        $a = ($container->privates['App\\ViewDefinitions\\LegacyHandler\\ViewDefinitionsHandler'] ?? $container->load('getViewDefinitionsHandlerService'));

        if (isset($container->privates['App\\ViewDefinitions\\DataProvider\\ViewDefinitionStateProvider'])) {
            return $container->privates['App\\ViewDefinitions\\DataProvider\\ViewDefinitionStateProvider'];
        }

        return $container->privates['App\\ViewDefinitions\\DataProvider\\ViewDefinitionStateProvider'] = new \App\ViewDefinitions\DataProvider\ViewDefinitionStateProvider($a);
    }
}
